// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompany("ACorns")]
[assembly: AssemblyCopyright("Copyright © Corneliu I. Tusnea (corneliu@acorns.com.au) 2016")]
[assembly: AssemblyVersion("0.0.1.0")]
[assembly: AssemblyFileVersion("0.0.1.0")]
